#!/usr/bin/env python3
"""Inject the shared navbar and footer as static HTML into every page.

Answer-engine crawlers (GPTBot, ClaudeBot, PerplexityBot) do not run
JavaScript, so a JS-injected navigation is invisible to them and every page
looks like an orphan. The markup lives here once and is written into the
files between markers, so pages stay static HTML.

Run after editing the nav or footer:  python3 tools/build-partials.py
"""

from __future__ import annotations

import os
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ASSET_VERSION = "202608281"
SITE = "https://olivabot.com"

NAV_START = "<!-- partial:navbar:start (generated by tools/build-partials.py) -->"
NAV_END = "<!-- partial:navbar:end -->"
FOOTER_START = "<!-- partial:footer:start (generated by tools/build-partials.py) -->"
FOOTER_END = "<!-- partial:footer:end -->"
CRUMB_START = "    <!-- partial:breadcrumb-schema:start (generated by tools/build-partials.py) -->"
CRUMB_END = "    <!-- partial:breadcrumb-schema:end -->"

THEME_ICONS = """<svg class="icon-moon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
                    <path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z"/>
                </svg>
                <svg class="icon-sun" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" style="display:none">
                    <circle cx="12" cy="12" r="5"/>
                    <line x1="12" y1="1" x2="12" y2="3"/>
                    <line x1="12" y1="21" x2="12" y2="23"/>
                    <line x1="4.22" y1="4.22" x2="5.64" y2="5.64"/>
                    <line x1="18.36" y1="18.36" x2="19.78" y2="19.78"/>
                    <line x1="1" y1="12" x2="3" y2="12"/>
                    <line x1="21" y1="12" x2="23" y2="12"/>
                    <line x1="4.22" y1="19.78" x2="5.64" y2="18.36"/>
                    <line x1="18.36" y1="5.64" x2="19.78" y2="4.22"/>
                </svg>"""


def navbar(page: str, asset: str) -> str:
    return f"""{NAV_START}
<header>
    <nav aria-label="Main navigation">
        <a href="{page}index.html" class="nav-brand">
            <img src="{asset}assets/images/logo.png" alt="Olivabot" class="nav-brand__logo" width="32" height="32">
            <span>Olivabot<span class="tm">&reg;</span></span>
        </a>
        <ul class="nav-links" id="nav-links">
            <li><a href="{page}services.html">Services</a></li>
            <li><a href="{page}work.html">Work</a></li>
            <li><a href="{page}projects.html">Projects</a></li>
            <li><a href="{page}about.html">About</a></li>
            <li><a href="{page}contact.html">Contact</a></li>
        </ul>
        <div class="nav-controls">
            <button class="theme-btn theme-toggle" id="theme-toggle" aria-label="Toggle dark mode" aria-pressed="false">
                {THEME_ICONS}
            </button>
        </div>
        <button class="nav-toggle" id="nav-toggle" aria-label="Open menu" aria-expanded="false" aria-controls="nav-links">
            <svg width="22" height="22" viewBox="0 0 22 22" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true">
                <line x1="3" y1="6" x2="19" y2="6"/>
                <line x1="3" y1="11" x2="19" y2="11"/>
                <line x1="3" y1="16" x2="19" y2="16"/>
            </svg>
        </button>
    </nav>
</header>
{NAV_END}"""


def footer(page: str, asset: str) -> str:
    return f"""{FOOTER_START}
<footer>
    <div class="footer-inner">
        <div class="footer-top">
            <a href="{page}index.html" class="footer-brand">
                <img src="{asset}assets/images/logo.png" alt="Olivabot" class="footer-brand__logo" width="40" height="40">
                <span>Olivabot<span class="tm">&reg;</span></span>
            </a>
            <nav class="footer-nav" aria-label="Footer navigation">
                <a href="{page}services.html">Services</a>
                <a href="{page}work.html">Work</a>
                <a href="{page}projects.html">Projects</a>
                <a href="{page}about.html">About</a>
                <a href="{page}dlab.html">DLAB</a>
                <a href="{page}contact.html">Contact</a>
            </nav>
        </div>
        <div class="footer-services">
            <a href="{page}services/firmware.html">Firmware &amp; embedded</a>
            <a href="{page}services/fintech.html">Fintech engineering</a>
            <a href="{page}services/software.html">Software for devices &amp; data</a>
            <a href="{page}services/agriculture-robotics.html">Agricultural consulting</a>
            <a href="{page}services/hosting.html">EU hosting &amp; maintenance</a>
        </div>
        <p class="footer-entity">
            <strong>Olivabot B.V.</strong> &mdash; De Boelelaan 1095a, 1081 HV Amsterdam, Netherlands.
            KVK 94493200. VAT NL866797373B01.
            <a href="mailto:services@olivabot.com">services@olivabot.com</a>.
            Remote work across the EU.
        </p>
        <div class="footer-bottom">
            <div class="footer-meta">
                <a href="mailto:info@olivabot.com" class="footer-email">info@olivabot.com</a>
                <span>&copy; 2026 Olivabot<span class="tm">&reg;</span>. All rights reserved.</span>
            </div>
            <div class="footer-right">
                <div class="footer-legal">
                    <a href="{page}legal/privacy.html">Privacy</a>
                    <a href="{page}legal/terms.html">Terms</a>
                    <a href="{page}legal/cookies.html">Cookies</a>
                    <a href="{page}legal/disclaimer.html">Disclaimer</a>
                </div>
                <div class="footer-controls">
                    <button class="theme-btn theme-toggle theme-btn--footer" id="footer-theme-toggle" aria-label="Toggle dark mode" aria-pressed="false">
                        {THEME_ICONS}
                    </button>
                </div>
            </div>
        </div>
    </div>
</footer>
{FOOTER_END}"""


def breadcrumb_schema(html: str, rel: Path) -> str | None:
    """Build BreadcrumbList JSON-LD from the breadcrumb the visitor can see.

    Google requires structured data to match visible content, so the schema is
    derived from the markup rather than maintained alongside it.
    """
    nav = re.search(
        r'<nav class="breadcrumb"[^>]*>(.*?)</nav>', html, re.DOTALL
    )
    if not nav:
        return None

    items = re.findall(
        r'<a href="([^"]+)"[^>]*>(.*?)</a>|<span>(.*?)</span>',
        nav.group(1),
        re.DOTALL,
    )
    if not items:
        return None

    page_url = f"{SITE}/{rel.as_posix()}"
    entries = []
    for position, (href, link_text, span_text) in enumerate(items, start=1):
        name = re.sub(r"<[^>]+>", "", link_text or span_text).strip()
        if not name:
            continue
        if href:
            target = os.path.normpath(rel.parent / href).replace(os.sep, "/")
            url = f"{SITE}/{target}"
        else:
            url = page_url
        entries.append(
            '            {"@type": "ListItem", "position": %d, '
            '"name": "%s", "item": "%s"}' % (position, name, url)
        )

    if len(entries) < 2:
        return None

    body = ",\n".join(entries)
    return f"""{CRUMB_START}
    <script type="application/ld+json">
    {{
        "@context": "https://schema.org",
        "@type": "BreadcrumbList",
        "itemListElement": [
{body}
        ]
    }}
    </script>
{CRUMB_END}"""


def replace_block(html: str, start: str, end: str, block: str) -> str:
    pattern = re.compile(re.escape(start) + r".*?" + re.escape(end), re.DOTALL)
    return pattern.sub(lambda _: block, html)


def process(path: Path) -> bool:
    rel = path.relative_to(ROOT)
    depth = len(rel.parts) - 1
    if depth == 1:  # en/*.html
        page, asset = "", "../"
    elif depth == 2:  # en/services/*.html etc.
        page, asset = "../", "../../"
    else:
        return False

    original = html = path.read_text(encoding="utf-8")

    if NAV_START in html:
        html = replace_block(html, NAV_START, NAV_END, navbar(page, asset))
    else:
        html = re.sub(
            r'[ \t]*<header id="navbar"></header>',
            lambda _: navbar(page, asset),
            html,
            count=1,
        )

    if FOOTER_START in html:
        html = replace_block(html, FOOTER_START, FOOTER_END, footer(page, asset))
    else:
        html = re.sub(
            r'[ \t]*<footer id="footer"></footer>',
            lambda _: footer(page, asset),
            html,
            count=1,
        )

    # One behaviour script replaces the two markup-injection scripts.
    html = re.sub(
        r'[ \t]*<script src="[^"]*assets/js/navbar\.js[^"]*"></script>\n'
        r'[ \t]*<script src="[^"]*assets/js/footer\.js[^"]*"></script>',
        lambda _: f'    <script src="{asset}assets/js/ui.js?v={ASSET_VERSION}"></script>',
        html,
    )
    html = re.sub(
        r'(assets/js/ui\.js\?v=)\d+',
        lambda m: m.group(1) + ASSET_VERSION,
        html,
    )
    html = re.sub(
        r'(assets/css/style\.css\?v=)\d+',
        lambda m: m.group(1) + ASSET_VERSION,
        html,
    )
    html = re.sub(
        r'(<link rel="sitemap"[^>]*href=")[^"]*(")',
        lambda m: m.group(1) + asset + "sitemap.xml" + m.group(2),
        html,
    )

    crumbs = breadcrumb_schema(html, rel)
    if CRUMB_START in html:
        html = replace_block(html, CRUMB_START, CRUMB_END, crumbs or "")
        html = re.sub(r"\n\s*\n(\s*</head>)", r"\n\1", html)
    elif crumbs:
        html = re.sub(
            r"[ \t]*</head>", lambda _: crumbs + "\n</head>", html, count=1
        )

    if html != original:
        path.write_text(html, encoding="utf-8")
        return True
    return False


def main() -> int:
    changed = []
    for path in sorted(ROOT.glob("en/**/*.html")):
        if process(path):
            changed.append(str(path.relative_to(ROOT)))

    print(f"updated {len(changed)} file(s)")
    for name in changed:
        print(f"  {name}")

    stale = [
        str(p.relative_to(ROOT))
        for p in sorted(ROOT.glob("en/**/*.html"))
        if 'id="navbar"' in p.read_text(encoding="utf-8")
        or "assets/js/navbar.js" in p.read_text(encoding="utf-8")
    ]
    if stale:
        print("\nWARNING: still using the JS navbar:", ", ".join(stale))
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
